[WIP] Expose functionality as a re-usable library
lsof-org/lsof pull request #279
Opened 2023-02-07 04:18 UTC by jiegec

This pr implements #268 by splitting code into two parts: liblsof(the library) and lsof(the cli). The pr is unfinished, but is half way done. It is a VERY BIG pull request and I try my best to maintain the lsof cli behavior. I am opening this pr to request for more comments. Progress:

- [x] Re-arrange directory structure, build liblsof using libtool.
- [x] Add initial library interface with Doxygen.
- [x] Move global and static variables to lsof context.
- [x] Rewrite LTbasic & LTszoff with liblsof.
- [x] Set visibility to hidden for internal functions of liblsof.
- [x] Migrate to Linux/Darwin/FreeBSD/NetBSD/OpenBSD. Solaris/OpenIndiana is planned.
- [ ] Support for AIX/HP-UX/SCO/UnixWare will be broken, but I do not have those environments to fix.
- [ ] Fix memory leaks.
- [ ] Replace all exit calls in liblsof with proper error reporting.
- [ ] Migrate more options from cli to liblsof until cli only uses public interface of liblsof.
- [ ] Write some utilities with liblsof as an example, maybe re-implement a netstat?

I'd love to see more comments on the API interface (You can find some at #268). Currently what's missing:

- Selection result reporting, I intend to implement as an array of tagged union, e.g. selection by pid success, selection by command name failed etc.
- Add optional fields to `struct lsof_file`, e.g. network address, TCP state. It can be implemented as an array of tagged union as well, or just list all of them with a valid mask. Should we expose the final NAME column content to the library user, or just provide the raw fields(e.g. `Lf->nm`, `Lf->nma`, `Lf->li` etc, see `printname`)?

2023-02-07 12:41 UTC, BenBE reviewed
The overall changes seem to be consistent and easy to follow for review (didn't manage to have a full look at everything, but the first ~20% seem sensible).

Minor remarks exist re code style, as well as some questions. Will continue my review later.

Looking at the changes overall leaves the impression, that this in places simplifies the existing code and removes a bit of repetition.

One implementation detail I noticed: Besides not calling `exit` inside the library, additionally writing to `stdout` and `stderr` should be handled via the context too (e.g. put some callback in the context to receive logging/error related information/output (e.g. dialect `hpux` -> `kmem/dproc.c`: The calls to `fprintf` inside `get_kernel_access` should be handled).

2023-02-07 12:41 UTC, BenBE commented on lib/dialects/aix/dnode.c
> +            return ((l) ? LSOF_LOCK_READ_FULL : LSOF_LOCK_READ_PARTIAL);
Style question: Any particular reason for those extra parens in the lines below?
```suggestion
            return (l) ? LSOF_LOCK_READ_FULL : LSOF_LOCK_READ_PARTIAL;
```

2023-02-07 12:41 UTC, BenBE commented on lib/dialects/darwin/Mksrc
> +mksrc
Maybe add a newline at EOF?

2023-02-07 12:41 UTC, BenBE commented on lib/dialects/freebsd/Mksrc
> +mksrc() {
Didn't another similar change cause this file to be shabanged as `/bin/bash` on another dialect?

2023-02-07 12:51 UTC, jiegec commented
> One implementation detail I noticed: Besides not calling `exit` inside the library, additionally writing to `stdout` and `stderr` should be handled via the context too (e.g. put some callback in the context to receive logging/error related information/output (e.g. dialect `hpux` -> `kmem/dproc.c`: The calls to `fprintf` inside `get_kernel_access` should be handled).

Sure, the current proposed solution is to output via `ctx->err` instead of `stderr`. The replace is not done yet because there are so many occurrences. If the library user wants to collect the output, `fmemopen` can be used.

2023-03-10 05:58 UTC, masatake commented
Incredible work!

2023-03-13 20:48 UTC, BenBE commented
Great work so far and even though I didn't continue yet with a follow up review for the parts I didn't get to in my first review, I'm still somewhat following this quite closely.

That said, it's kinda hard to review this set of changes realistically due to the sheer amount of affected files and number of commits. One theme I remarked in my first review concerns the tiny clean-ups that are happening along the way. They are necessary, but a more systematic way to know if a commit is just cleanup or affects the project structure would be good; ideally the mere fixups should be on a different PR so they can be skipped more easily. As much as I like this PR I don't feel confident in its current state that a review is likely to find any fallout or oder (un)intended (hidden) changes apart from the most basic ones. Thus it's probably best to mark this PR as draft for now and reorder/rework the individual commits once all pieces for this change are in place.

As far as I noticed in the commits so far, there are essentially four phases the commits can be sorted into:
* Cleanup / preparation
* Documentation updates
* Build system adjustments
* Code/data structure changes

Given that the last phase (actual code/data structure changes) is the main aspect of this PR, I'd somehow suggest having at least the cleanup and documentation issues be separated into a separate branch. This allows to have the project benefit from these (small) changes even long before the whole library PR is finalized.

I'll try to start a second attempt at reviewing the changes accumulated so far soon. So in case there's sth I should wait for before starting just drop me a note.

2023-04-02 20:17 UTC, BenBE commented
NB: @jiegec Quick question as I don't seem to see it in the changes, but kinda expected to: Will there be some configuration file(s) for `pkg-config` with the new library, or will using the lib externally somewhat boil down on fixed (include) paths for finding the necessary ingredients?

2023-04-03 00:25 UTC, jiegec commented
> NB: @jiegec Quick question as I don't seem to see it in the changes, but kinda expected to: Will there be some configuration file(s) for `pkg-config` with the new library, or will using the lib externally somewhat boil down on fixed (include) paths for finding the necessary ingredients?

Okay, I will add `.pc` file to locate the new library. I am currently working on the second part at branch library-part2: adding context arguments.

2023-04-13 07:14 UTC, BenBE requested changes
Please be more careful with your changes.

2023-04-13 07:14 UTC, BenBE commented on lib/dialects/hpux/kmem/dnode2.c
> +static int is_rootFid, (struct vcache * vc int *rfid);
Stray comma

2023-04-13 07:14 UTC, BenBE commented on lib/dialects/freebsd/dsock.c
> +static int ckstate           (struct lsof_context * ctx, struct xtcpcb *pcb, int fam);
Remove whitespace?

2023-04-13 07:14 UTC, BenBE commented on lib/dialects/freebsd/dproto.h
> +extern char *get_nlist_path, (struct lsof_context * ctx int ap);
Stray comma

2023-04-13 07:14 UTC, BenBE commented on lib/dialects/aix/dproto.h
> +extern int readj2lino, (struct gnode * ga struct l_ino * li);
Stray comma

2023-04-13 07:14 UTC, BenBE commented on lib/dialects/sun/dnode.c
> +static char *ent_fa, (KA_T * a1, KA_T *a2, char *d int *len);
Stray comma

2023-04-13 07:14 UTC, BenBE commented on lib/dialects/sun/dnode1.c
> +static int is_rootFid, (struct vcache * vc int *rfid);
Stray comma

2023-04-13 07:14 UTC, BenBE commented on lib/dialects/sun/dnode2.c
> +static char *add2em, (char *em, char *fmt char *arg);
Stray comma

2023-04-13 07:14 UTC, BenBE commented on lib/dialects/sun/dnode2.c
> +static char *ckptr           (char *em, char *ptr, int len, int slen, char *nm);
Remove whitespace?

2023-04-13 07:14 UTC, BenBE commented on lib/dialects/sun/dproto.h
> +extern struct l_vfs *readvfs,
Stray comma

2023-04-13 07:14 UTC, BenBE commented on lib/dialects/sun/dproto.h
> +extern struct hostent *gethostbyname2, (const char *nm int proto);
Stray comma

2023-04-13 07:14 UTC, BenBE commented on lib/dialects/sun/dproto.h
> +extern int process_VSOCK,
Stray comma

2023-04-13 07:14 UTC, BenBE commented on lib/dialects/sun/dsock.c
> +static int read_udp_t           (struct lsof_context * ctx, KA_T ua, udp_t *uc);
Remove whitespace?

2023-04-13 07:14 UTC, BenBE commented on lib/proto.h
> +extern pxinfo_t *find_pepti,
Stray comma

2023-04-13 07:14 UTC, BenBE commented on tests/LTdnlc.c
> +static char *FindLsofCwd, (int *ff, LTdev_t *cwddc char *ibuf);
Stray comma

2023-04-13 07:14 UTC, BenBE commented on tests/LTlib.c
> +static X2DEV_T x2dev, (char *x char **em);
Stray comma

2023-04-13 07:14 UTC, BenBE commented on tests/LTlib.c
> +static int GetOpt           (int ct, char *opt[], char *rules, char **em, char *pn);
Remove whitespace?

2023-04-13 07:14 UTC, BenBE commented on tests/LTlock.c
> +static char *tstwlsof, (char *opt char *xlk);
Stray comma

2023-04-13 07:14 UTC, BenBE commented on tests/LTnlink.c
> +static char *FindFile, (char *opt, int *ff, int ie, LTdev_t *tfdc                                   char *ibuf, char *xlnk, char *szbuf);
Stray comma

2023-04-13 07:14 UTC, BenBE commented on tests/LTszoff.c
> +static char *testlsof, (int tt, char *opt char *xval);
Stray comma

2023-04-13 07:14 UTC, BenBE commented on tests/LsofTest.h
> +extern void StopLsof (void);
Stray comma

2023-04-13 07:24 UTC, jiegec commented
> Please be more careful with your changes.

Thanks, I was removing `_PROTOTYPE` via regex, but the matching does not work well on multiline programs.. I do not plan to merge this large pr, but take effort to complete in parts.

2023-04-13 07:24 UTC, closed without merging

2023-04-13 07:28 UTC, BenBE reviewed
Why are some function signatures reverted back to K&R style?

2023-04-13 07:28 UTC, BenBE commented on lib/dialects/hpux/kmem/dnode1.c
> +int *rdevs;        /* raw device status receiver */
Why not rewrite this to more modern C like with so many other function declarations?

2023-04-13 07:39 UTC, BenBE commented
NB: Ah, k. Maybe have a look at `git rerere`, which should help with such situations. Also I noticed `kdiff3` usually does a quite good job at resolving most conflicts correctly automatically.

2023-05-04 13:30 UTC, BenBE commented
@jiegec Any further open aspects/items for this feature? AFAICS the bullet list in the first post has not been checked off completely.