Expose functionality as a re-usable library - Part 2
lsof-org/lsof pull request #284
Opened 2023-04-03 01:38 UTC by jiegec

Part 2 of #279: add `lsof_context * ctx` argument to functions.

2023-04-03 21:27 UTC, BenBE requested changes
Please re-check if all functions properly pass the context around. Several places seem to be missing the `ctx` argument.

2023-04-03 21:28 UTC, BenBE requested changes
Please re-check if all functions properly pass the context around. Several places seem to be missing the `ctx` argument.

2023-04-08 17:46 UTC, BenBE requested changes
Still a lot of functions missing the `ctx` argument …
Please report back, once you have completed that cleanup.

2023-04-08 17:46 UTC, BenBE commented on lib/dialects/aix/dfile.c
> +struct l_vfs *readvfs(struct vnode *vn) /* vnode */
Missing `ctx` argument

2023-04-08 17:46 UTC, BenBE commented on lib/dialects/aix/dnode.c
> +char isglocked(struct gnode *ga) /* local gnode address */
Missing `ctx` argument

2023-04-08 17:46 UTC, BenBE commented on lib/dialects/aix/dnode.c
> +void process_node(KA_T va) /* vnode kernel space address */
Missing `ctx` argument

2023-04-08 17:46 UTC, BenBE commented on lib/dialects/aix/dnode.c
> +void process_shmt(KA_T sa) /* shared memory transport node struct
Missing `ctx` argument

2023-04-08 17:46 UTC, BenBE commented on lib/dialects/aix/dnode1.c
> +static struct volume *getvolume(struct VenusFid *f, /* file ID pointer */
Missing `ctx` argument

2023-04-08 17:46 UTC, BenBE commented on lib/dialects/aix/dnode1.c
> +int hasAFS(struct vnode *vp) /* vnode pointer */
Missing `ctx` argument

2023-04-08 17:46 UTC, BenBE commented on lib/dialects/aix/dnode1.c
> +static int is_rootFid(struct vcache *vc, /* vcache entry */
Missing `ctx` argument

2023-04-08 17:46 UTC, BenBE commented on lib/dialects/aix/dnode1.c
> +int readafsnode(KA_T va,            /* kernel vnode address */
Missing `ctx` argument

2023-04-08 17:46 UTC, BenBE commented on lib/dialects/aix/dnode2.c
> +int readj2lino(struct gnode *ga, /* gnode address */
Missing `ctx` argument

2023-04-08 17:46 UTC, BenBE commented on lib/dialects/aix/dproc.c
> +        Error(ctx);
Missing `ctx` argument

2023-04-08 17:46 UTC, BenBE commented on lib/dialects/aix/dproc.c
> +        Error(ctx);
Missing `ctx` argument

2023-04-09 01:36 UTC, jiegec commented
> Still a lot of functions missing the `ctx` argument … Please report back, once you have completed that cleanup.

Thanks, I don't have AIX, HP-UX or UnixWare environment, It is hard to enumerate those places without compilers help.

2023-04-10 11:06 UTC, jiegec commented
I installed SCO OpenServer 5 in VM, but it is too hard to use from 2023's perspective.. I installed git, make etc. but was unable to build lsof. I surrender.

2023-04-12 06:01 UTC, merged

2023-04-12 06:23 UTC, BenBE commented
Looking through the diff, there are (still) several (easy to spot) places, where the `ctx` is used, but not provided as an argument. This will likely give a warning, but given that there's a global variable in the main process somewhat compile nonetheless. This is extremely unclean code style, and does not usually require to compile the code (TBF: I did just have a look at the code and spotted those issues). I know hpux, aix and several other platforms are rare to come by for testing, but a minimum of diligence should be used when working on such patch sets.

2023-04-12 06:24 UTC, jiegec commented
The global variable in the main process is removed.

2023-04-12 06:30 UTC, BenBE commented
Thanks for this note.

Seems as if GH was showing me some outdated (partial) version of the diff earlier for this patch; looks much cleaner now.